Reference Mono.Security.dll for tlstest.cs
`tlstest.cs` requires `Mono.Security.dll`.

Lacking `-r:Mono.Security.dll` results in compilation errors:

	tlstest.cs(23,21): error CS0234: The type or namespace name `Protocol' does not exist in the namespace `Mono.Security'. Are you missing an assembly reference?